-- Adicionar coluna GOOGLE_ID se não existir
ALTER TABLE USUARIOS ADD COLUMN IF NOT EXISTS GOOGLE_ID VARCHAR(255) NULL;

-- Tornar campos opcionais para usuários OAuth
ALTER TABLE USUARIOS MODIFY SENHA_USUARIO VARCHAR(255) NULL;
ALTER TABLE USUARIOS MODIFY CELULAR_USUARIO VARCHAR(100) NULL;
ALTER TABLE USUARIOS MODIFY CPF_USUARIO VARCHAR(15) NULL;
ALTER TABLE USUARIOS MODIFY LOGRADOURO_USUARIO VARCHAR(100) NULL;
ALTER TABLE USUARIOS MODIFY BAIRRO_USUARIO VARCHAR(30) NULL;
ALTER TABLE USUARIOS MODIFY CIDADE_USUARIO VARCHAR(30) NULL;
ALTER TABLE USUARIOS MODIFY UF_USUARIO CHAR(2) NULL;
ALTER TABLE USUARIOS MODIFY CEP_USUARIO VARCHAR(15) NULL;