CREATE TABLE USUARIOS (
    ID_USUARIO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(70) NOT NULL,
    EMAIL_USUARIO VARCHAR(35) UNIQUE NOT NULL, 
    CELULAR_USUARIO CHAR(11) UNIQUE NOT NULL, 
    CPF_USUARIO CHAR(11) UNIQUE NOT NULL,
    LOGRADOURO_USUARIO VARCHAR(100) NOT NULL,
    BAIRRO_USUARIO VARCHAR(30) NOT NULL, 
    CIDADE_USUARIO VARCHAR(30) NOT NULL, 
    UF_USUARIO CHAR(2) NOT NULL, 
    CEP_USUARIO CHAR(8) NOT NULL,
    SENHA_USUARIO CHAR(6) NOT NULL,
    TIPO_USUARIO CHAR(1) NOT NULL
);
     
CREATE TABLE CLIENTES (
    id_cliente INT AUTO_INCREMENT PRIMARY KEY,
    cpf_cliente VARCHAR(14) UNIQUE NOT NULL,
    id_usuario INT UNSIGNED NOT NULL, 
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS (ID_USUARIO) 
);

CREATE TABLE VENDEDORES (
    id_vendedores INT AUTO_INCREMENT PRIMARY KEY,
    tipo_pessoa CHAR (2) NOT NULL,
    digito_pessoa VARCHAR(14) UNIQUE NOT NULL,
    id_usuario INT UNSIGNED NOT NULL, 
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS (ID_USUARIO) 
);

CREATE TABLE CATEGORIAS (
    id_categoria INT AUTO_INCREMENT PRIMARY KEY,
    nome_categoria VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUTOS (
    id_prod INT AUTO_INCREMENT PRIMARY KEY,
    nome_prod VARCHAR(255) NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,
    qtde_estoque INT NOT NULL,
    prazo_validade DATE,
    img_prod VARCHAR(255), 
    id_categoria INT NOT NULL,
    FOREIGN KEY (id_categoria) REFERENCES CATEGORIAS (id_categoria)
);

CREATE TABLE PEDIDOS (
    id_pedido INT AUTO_INCREMENT PRIMARY KEY,
    id_cliente INT NOT NULL,
    dt_pedido DATE NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE) 
);

CREATE TABLE PEDIDOS_PRODUTOS (
    ID_PEDIDO INT NOT NULL,
    ID_PROD INT NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO),
    FOREIGN KEY (ID_PROD) REFERENCES PRODUTOS (ID_PROD)
);

ALTER TABLE USUARIOS
MODIFY SENHA_USUARIO VARCHAR(255) NOT NULL,
ADD AUTH_TOKEN VARCHAR(255) NULL;
ALTER TABLE USUARIOS MODIFY EMAIL_USUARIO VARCHAR(100) NOT NULL;
ALTER TABLE USUARIOS MODIFY CELULAR_USUARIO VARCHAR(100) NOT NULL;
ALTER TABLE USUARIOS MODIFY CPF_USUARIO VARCHAR(15) NOT NULL;
ALTER TABLE USUARIOS MODIFY CEP_USUARIO VARCHAR(15) NOT NULL;

-- Inserir categorias
INSERT INTO CATEGORIAS (nome_categoria) VALUES 
('Frutas'),
('Verduras'),
('Legumes');

-- Inserir produtos
INSERT INTO PRODUTOS (nome_prod, valor_unitario, qtde_estoque, img_prod, id_categoria) VALUES 
('Abacaxi Pérola', 9.85, 50, 'imagens/abacaxi.png', 1),
('Ameixa Importada', 2.99, 100, 'imagens/ameixa.png', 1),
('Alface Crespa', 2.99, 80, 'imagens/alface.png', 2),
('Brócolis Ninja', 9.70, 60, 'imagens/brocolis.png', 3);

-- Inserir usuários vendedores
INSERT INTO USUARIOS (NOME_USUARIO, EMAIL_USUARIO, CELULAR_USUARIO, CPF_USUARIO, LOGRADOURO_USUARIO, BAIRRO_USUARIO, CIDADE_USUARIO, UF_USUARIO, CEP_USUARIO, SENHA_USUARIO, TIPO_USUARIO) VALUES 
('João Silva', 'joao@fazendaorganica.com', '11987654321', '12345678901', 'Estrada Rural 123', 'Zona Rural', 'Ibiuna', 'SP', '18150000', '$2b$10$example1', 'V'),
('Maria Santos', 'maria@verdurasfrescas.com', '11876543210', '98765432109', 'Sítio das Flores', 'Centro', 'Piedade', 'SP', '18170000', '$2b$10$example2', 'V'),
('Carlos Oliveira', 'carlos@frutasdocampo.com', '11765432109', '11122233344', 'Fazenda Boa Vista', 'Rural', 'Tapiraí', 'SP', '18180000', '$2b$10$example3', 'V');

-- Inserir vendedores
INSERT INTO VENDEDORES (tipo_pessoa, digito_pessoa, id_usuario) VALUES 
('PF', '123.456.789-01', (SELECT ID_USUARIO FROM USUARIOS WHERE EMAIL_USUARIO = 'joao@fazendaorganica.com')),
('PJ', '12.345.678/0001-90', (SELECT ID_USUARIO FROM USUARIOS WHERE EMAIL_USUARIO = 'maria@verdurasfrescas.com')),
('PF', '111.222.333-44', (SELECT ID_USUARIO FROM USUARIOS WHERE EMAIL_USUARIO = 'carlos@frutasdocampo.com'));